name: Documentation

on:
  push:
    branches: [ master ]

env:
  FILE_NAME: Reactjs-Interview-Questions-Part-1'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-20.04    
    steps:      
      - uses: actions/checkout@v2          
  
